### ISSUE TITLE
Issue with other sources than Youtube

### ISSUE THREAD

**Issue by NerosTie** [kevinpapst/freshrss-youtube#1]
The extension is in conflict with Vimeo (for example). You have the embedded video from Vimeo plus an other one from the extension which tries to locate the video on Youtube. Maybe it's the same thing with other sources like Dailymotion but I didn't try.

![image](https://cloud.githubusercontent.com/assets/4572452/20818616/1943be60-b82f-11e6-9e1e-721e9daca530.png)

EDIT: In fact, it's in conflit with everything! On every feed, the extension tries to find a video on Youtube, even feeds which are pure text.

**Comment by kevinpapst** [comment]
Whoops, it might habe been a little late yesterday. Thanks for the info! 
I will fix that ASAP.

**Comment by kevinpapst** [comment]
That was a stupid beginners mistake^^ 
I just edited the file online without re-testing, if you wanna give it a try go ahead. 
Otherwise I will check it tonight with all kinds of different feeds and let you.

**Comment by kevinpapst** [comment]
Fixed with 921bb7366ab40ea698fee07c15b14fc3433ae8cc

**Comment by NerosTie** [comment]
It works, thanks!
