### ISSUE TITLE
Some channels are not directly recognized

### ISSUE THREAD

**Issue by javerous** [kevinpapst/freshrss-youtube#15]
Hello.

So I'm playing with your extension (the version released at the date of this ticket, i.e. 0.9), and some channels are rejected when I try to subscribe to them (some of them seems to works).

They all work if I directly add the feed URL (`https://www.youtube.com/feeds/videos.xml?channel_id=XXX`).

By example
— `https://www.youtube.com/channel/UC3l2JpG0vN8xMkvvfCwavcQ`
→ Error: ```The newsfeed could not be added. Check FreshRSS logs for details. You can try force adding by appending #force_feed to the URL.```
→ Log: ```A feed could not be found at `https://www.youtube.com/channel/UC3l2JpG0vN8xMkvvfCwavcQ`; the status code is `200` and content-type is `text/html; charset=utf-8` [https://www.youtube.com/channel/UC3l2JpG0vN8xMkvvfCwavcQ]```

— `https://www.youtube.com/channel/UC8Ux-LOyEXeioYQ4LFzpBXw`
→ Error: same.
→ Log: same.

I have other examples if needed.

Is it a known problem ?

**Comment by kevinpapst** [comment]
Hm, I thought this was fixed. 
ping @marienfressinaud can you verify that?

**Comment by javerous** [comment]
@kevinpapst Thanks.

And now I saw another errors, not sure why... Is it possible I badly configured the extension ? (it appear in extensions panel, it's enabled, and all settings are set to the default).

```
Unknown error for feed [https://www.youtube.com/channel/UC8Ux-LOyEXeioYQ4LFzpBXw]
```

<img width="712" alt="Screenshot 2020-01-10 at 17 09 33" src="https://user-images.githubusercontent.com/1971659/72167739-0648ca00-33cc-11ea-8445-367679cb9931.png">

**Comment by kevinpapst** [comment]
Are your running the latest FRSS version?

**Comment by javerous** [comment]
Yes, version `1.15.3`.

**Comment by marienfressinaud** [comment]
They all work for me, and the errors look like the extension isn't up to date. Can you verify the code of the `extensions/xExtension-YouTube/extension.php` file (lines 47 - 60) look like this: https://github.com/kevinpapst/freshrss-youtube/blob/master/xExtension-YouTube/extension.php#L47-L60 ?

**Comment by javerous** [comment]
Yes, it's exactly the same... Can it be something in my PHP config ? `preg_match` seems pretty standard (and would probably raise other kind of error if it was failing…)

**Comment by marienfressinaud** [comment]
Ha, I know: the hook being used here has been [added](https://github.com/FreshRSS/FreshRSS/commit/08c6a1bdc16d7cc9717788172251c6e5eae3e443) after the release of the 1.15.3. You should either wait for the next release of FRSS, or update FRSS with the latest `master` version

**Comment by javerous** [comment]
Okay, good catch then ! Thank you :)

**Comment by kevinpapst** [comment]
Lets keep it open until the next FRSS release is available

**Comment by kevinpapst** [comment]
3 years later I expect this has been resolved
