### ISSUE TITLE
thumbnail still showing under video player

### ISSUE THREAD

**Issue by bwees** [kevinpapst/freshrss-youtube#21]
<img width="439" alt="Screenshot 2023-08-03 at 1 09 07 PM" src="https://github.com/kevinpapst/freshrss-youtube/assets/12686250/5357c0f2-f22b-4a8f-b964-58ee0f601438">

The thumbnail and content is still showing under the video embed even after I have show content deselected. I tried to nail down the bug and it appears that even if you just pass the iframe code (or even text for that matter) from here: 

https://github.com/kevinpapst/freshrss-youtube/blob/master/xExtension-YouTube/extension.php#L186

FreshRSS still renders the feed content beneath the video player. When I turn on show content I basically get the player and then the description then the thumbnail and description again:
<img width="312" alt="Screenshot 2023-08-03 at 1 15 27 PM" src="https://github.com/kevinpapst/freshrss-youtube/assets/12686250/2cf2647b-2a78-4979-b538-d9170b8a61b9">

It appears as if FreshRSS is appending the feed content regardless of what this extension outputs. Is this due to the use of _content variable when setting the html?

I am on v1.21.0 that was released 4 days ago so it may be a freshRSS bug, I will try to go to 1.20.0 and see if that fixes it

**Comment by bwees** [comment]
It appears to fix itself on 1.20.2, will open a freshRSS issue and mention this issue here.

**Comment by kevinpapst** [comment]
I am seeing the same issue. But I didn't have the time to investigate.

What I can tell you: the setting worked properly in the past. You either had the video player alone or (if setting was active) the player and the content below. 

The thumbnail is new, also the fact that the content is injected, no matter what.
There was some kind of change in FreshRSS core.

**Comment by kevinpapst** [comment]
Closing here.
If the issue persists, please re-open the issue at https://github.com/FreshRSS/Extensions
