### ISSUE TITLE
A lot of errors in logs

### ISSUE THREAD

**Issue by NerosTie** [kevinpapst/freshrss-youtube#4]
In logs, I have many errors like that:

```
yt_player_height does not exist in configuration
yt_player_width does not exist in configuration
```
How can I fix these issues?

**Comment by kevinpapst** [comment]
Could you try to edit the plugin configuration once in the admin section. 
If the error doesn't go away after saving and reloading the page, let me know.

**Comment by NerosTie** [comment]
The 2 fields are empty but I don't know what to put.

**Comment by kevinpapst** [comment]
Just put numbers for width and length into it. Default values can be seen here:
https://github.com/kevinpapst/freshrss-youtube/blob/master/xExtension-YouTube/extension.php#L16

So try 560 for width and 315 for height.

**Comment by kevinpapst** [comment]
Btw, which version for FreshRSS and the Youtube extension are you running?

**Comment by NerosTie** [comment]
It's ok with 560 for width and 315 for height, thanks!
